image:
  repository: ghcr.io/kikomiguelmendes/do_2_f
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

registry:
  createImagePullSecret: false

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: minikube.test
      paths:
        - path: /GitOps-Starter
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10